import os
import csv
from datetime import datetime

# Import the neondb_serverless package
try:
    from neondb_serverless import sql
except ImportError:
    print("Installing neondb_serverless...")
    import subprocess
    subprocess.check_call(['pip', 'install', 'neondb_serverless'])
    from neondb_serverless import sql

# Get database URL from environment
database_url = os.environ.get('DATABASE_URL')
if not database_url:
    raise Exception("DATABASE_URL environment variable is not set")

# Create SQL client
db = sql(database_url)

# CSV data as string (embedded from the uploaded file)
csv_data = """id,area,title,description_en,description_ms,furnishing_en,furnishing_ms,price,sqft,bedroom,move_in_date,agent_phone,image_url,map_url
1,KLCC,"Four Seasons Place","Luxury 2-bedroom condo with city views. KLCC LRT station is a 5-min walk, Suria KLCC and Pavilion KL nearby. KLCC Park is perfect for jogging and leisure.","Kondo mewah 2 bilik dengan pemandangan bandar. Stesen LRT KLCC 5 minit berjalan kaki, Suria KLCC dan Pavilion KL berhampiran. Taman KLCC sesuai untuk berjoging dan bersantai.","Fully Furnished","Berperabot Lengkap",3500.00,1345,2,2025-12-01,6012-3456789,https://www.theplacekl.com/assets/visuals/interior/01.jpg,https://maps.app.goo.gl/cjzKASr827kt9SSp6
2,KLCC,"The Troika","Spacious 3-bedroom unit. Walk to Persiaran KLCC MRT and enjoy nearby restaurants and boutiques. Suria KLCC mall within 10 minutes.","Unit 3 bilik yang luas. Berjalan kaki ke MRT Persiaran KLCC dan menikmati restoran serta butik berhampiran. Pusat beli-belah Suria KLCC dalam 10 minit.","Partially Furnished","Berperabot Separa",5000.00,2300,3,2026-01-15,6011-2233445,https://www.expatgo.com/my/wp-content/uploads/2016/03/the-troika-2.jpg,https://maps.app.goo.gl/8BNuindt3p7uZG9dA
3,KLCC,"Le Nouvel","2-bedroom serviced residence, 1,830 sqft. Close to KLCC LRT, Suria KLCC, Avenue K, and KLCC Park.","Residence servis 2 bilik, 1,830 kaki persegi. Dekat dengan LRT KLCC, Suria KLCC, Avenue K, dan Taman KLCC.","Partially Furnished","Berperabot Separa",3000.00,1830,2,2025-11-20,6012-9987766,https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2d/91/a9/bf/executive-room-with-sofa.jpg?w=1400&h=-1&s=1,https://maps.app.goo.gl/QTaNPotmzJkmg5Gx9
4,KLCC,Aria,"1-bedroom serviced apartment, fully furnished. Few minutes walk to KLCC LRT, many F&B outlets nearby, Suria KLCC and Jalan Ampang close.","Apartmen servis 1 bilik, lengkap berperabot. Beberapa minit berjalan kaki ke LRT KLCC, banyak kedai F&B berhampiran, Suria KLCC dan Jalan Ampang dekat.","Fully Furnished","Berperabot Lengkap",1500.00,1159,1,2025-12-05,6013-5559988,https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://storage.googleapis.com/msgsndr/urgz3ehyjizBb14KYhgn/media/67580c64b5c094d988512e24.png,https://maps.app.goo.gl/pkGmKLcy6rgGLXuMA
5,KLCC,"St Mary Residences","3-bedroom corner unit with views. Close to MRT/LRT, Suria KLCC, local shops on Jalan Stonor, and KLCC Park.","Unit sudut 3 bilik dengan pemandangan. Dekat MRT/LRT, Suria KLCC, kedai tempatan di Jalan Stonor, dan Taman KLCC.","Fully Furnished","Berperabot Lengkap",4500.00,1131,3,2026-02-01,6014-6673344,https://lh3.googleusercontent.com/gps-cs-s/AG0ilSySgrih9dSt4Auaz8YnDSQZej9iVlWs6EU0M4uHXrgdrqZeiY36dw7G9vzRvFf567iWVOn2tp64sq3u1C83dzLjrVxAKeFX8Ho8RwoCQKGcz-pFeGZedkuZj2KfQbvk3gEz_OrQ=s1360-w1360-h1020-rw,https://maps.app.goo.gl/F7scfoVexYrEYJSu7
6,"Bukit Bintang","The Robertson Condo","1‑bedroom 538 sq ft condo in The Robertson, Bukit Bintang. Fully furnished with living/dining furniture, washer, fridge. Walking distance to Pavilion KL, Lot 10, and Bukit Bintang MRT / monorail / bus stops.","Kondo 1 bilik 538 kaki persegi di The Robertson, Bukit Bintang. Lengkap berperabot — perabot ruang tamu / makan, mesin basuh, peti sejuk. Berjalan kaki ke Pavilion KL, Lot 10, dan stesen tren / bas Bukit Bintang.","Fully Furnished","Berperabot Lengkap",2200.00,538,1,2025-12-01,6016-8873984,https://pix8.agoda.net/hotelImages/33222004/661180543/4a66d546ddf9e1e88047879767db0900.jpg?ce=0&s=1024x,https://maps.app.goo.gl/CRPsxSk89XGLhBY8A
7,"Bukit Bintang","Verticas Residensi","2-bedroom, 2-bath unit (1,023 sqft) in Verticas Residensi, Jalan Ceylon. High‑floor, fully furnished with modern ID design. Amenities include gym, swimming pool, sauna, yoga room, BBQ area and 24‑hour security. Very well connected — walking distance to Bukit Bintang shopping malls like Pavilion, Sungei Wang, and Jalan Ceylon F&B spots. Close to public transport (monorail, MRT, buses).","Unit 2 bilik, 2 bilik mandi (1,023 kaki persegi) di Verticas Residensi, Jalan Ceylon. Tingkat tinggi, lengkap berperabot dengan rekaan moden. Kemudahan termasuk gim, kolam renang, sauna, bilik yoga, kawasan BBQ dan keselamatan 24‑jam. Lokasi sangat strategik — berjalan kaki ke pusat membeli-belah Bukit Bintang seperti Pavilion, Sungei Wang, dan kawasan F&B Jalan Ceylon. Dekat dengan pengangkutan awam (monorel, MRT, bas).","Fully Furnished","Berperabot Lengkap",4500.00,1023,2,2025-11-15,6017-7482952,https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWkfBohPjrNmQBkCfDtKq9umXVadz9n_itYw&s,https://maps.app.goo.gl/2ezezyotEXgzuZwLA
8,"Bukit Bintang","Laman Ceylon","Fully furnished with air-conditioning, kitchen hob/hood, and bathtub. 24‑hour security, gym, landscaped garden. Very central — walking distance to Bukit Bintang, Jalan Alor, Pavilion KL.","Lengkap berperabot dengan penghawa dingin, dapur, dan tab mandi. Keselamatan 24 jam, gim dan taman landskap. Lokasi sangat strategik — berjalan kaki ke Bukit Bintang, Jalan Alor dan Pavilion KL.","Fully Furnished","Berperabot Lengkap",5000.00,1604,3,2025-12-01,6011-22221112,https://cf.bstatic.com/xdata/images/hotel/max1024x768/713093428.jpg?k=96fc397d19def0c6b7412f5b1ab72e10c930671b46b2bfcccddb05a1ca624ace&o=,https://maps.app.goo.gl/1XgaJRYZxPKmBJf97
9,"Bukit Bintang","Menara Bukit Ceylon","Spacious 3‑bedroom / 2 bath unit, ~1,500 sq ft, fully furnished. Located on Jalan Ceylon, near Bukit Bintang's shopping belts and nightlife. Well-connected by buses and close to monorail / MRT exits. Amenities: pool, gym, security, parking.","Unit luas 3 bilik / 2 bilik mandi, kira-kira 1,500 kaki persegi, lengkap berperabot. Terletak di Jalan Ceylon, dekat dengan pusat beli-belah Bukit Bintang dan tempat makan malam. Sambungan pengangkutan awam baik dengan bas dan monorel / MRT berdekatan. Kemudahan termasuk kolam, gim, keselamatan dan tempat letak kereta.","Fully Furnished","Berperabot Lengkap",3500.00,1500,3,2025-11-06,6019-5101499,https://d5dkjitd3iude.cloudfront.net/eyJidWNrZXQiOiJ3d3cudGhlZWRnZXByb3BlcnR5LmNvbS5teSIsImtleSI6InMzZnMtcHVibGljXC80MDcwNV8xNjk2Mzk0NTk3XzVFZGdQcm81X2ltZzIwMjMwOTEwMTUzMTUxXzAuanBnIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjozNjUsImhlaWdodCI6MjQzLCJmaXQiOiJjb3ZlciJ9fX0=,https://maps.app.goo.gl/C6vNygibWkY29AXx5
10,"Bukit Bintang","Sixceylon (6 Ceylon)","1‑bedroom unit, ~696 sq ft, partially or fully furnished depending on listing. Very centrally located on Jalan Ceylon, with good access to Bukit Bintang shopping (Pavilion, Lot 10), plenty of F&B, and public transport nearby. Amenities include gym, pool, 24‑hour security.","Unit 1 bilik, kira‑kira 696 kaki persegi, berperabot sebahagian atau penuh bergantung pada iklan. Terletak di Jalan Ceylon, sangat strategik dekat Bukit Bintang dengan pusat beli-belah Pavilion, Lot 10, banyak makanan dan pengangkutan awam. Kemudahan termasuk gim, kolam renang dan pengawal 24 jam.","Fully Furnished","Berperabot Lengkap",2800.00,696,1,2025-12-01,6012-9981183,https://cdn.rnudah.com/images/plain/cf607a3ca768970cef17139cea9d423b-2946840980254481824.jpg,https://maps.app.goo.gl/iFrB2mdp2tkEXe9v8
11,"Mont Kiara","Inspirasi Mont Kiara","3-bedroom, 2 bathroom condo (~940 sq ft) in Mont Kiara. Fully furnished: smart TV, Wi-Fi, fridge, stove, washer/dryer. Facilities: pool, gym, sauna, playground, multipurpose hall and 24-hour security. Close to Publika, Arcoris Plaza, 1 Mont Kiara.","Pangsapuri 3 bilik, 2 bilik mandi (~940 kaki persegi) di Mont Kiara. Lengkap berperabot: smart TV, Wi‑Fi, peti sejuk, dapur, mesin basuh / pengering. Kemudahan: kolam, gim, sauna, taman permainan, dewan pelbagai guna dan keselamatan 24 jam. Dekat dengan Publika, Arcoris Plaza, 1 Mont Kiara.","Fully Furnished","Berperabot Lengkap",3800.00,940,3,2025-11-10,6012-5109150,https://montkiara.properties/wp-content/uploads/2023/02/Inspirasi-Mont-Kiara-1015sf-06022023-2.jpg?v=1675683788,https://maps.app.goo.gl/y7nQAE993TcomU9f7
12,"Mont Kiara","Pavilion Hilltop","High-end condo with resort-style facilities, near French International School.","Kondominium mewah dengan kemudahan gaya resort, berhampiran Sekolah Antarabangsa Perancis. ","Fully Furnished","Berperabot Lengkap",5500.00,1200,3,2026-02-01,"6010-6789012 ",https://images.openai.com/static-rsc-1/DsW5e2k5JhvYVTk6MKu49MJA0OHmWo0iywlQMWjarWA6UCO96oLQkHvmnAdsGQYZnK7YI6Xvkr_F1ItNISaqdZ8WQMfdroVZvKP0B1X6gFmtFpE5zHE_M1aiDngBpTUwRmwEyR9b56ZEsNDkwKCZPw,"https://www.google.com/maps/place/Pavilion+Hilltop,+Mont+Kiara/"
13,"Mont Kiara","Arcoris Mont Kiara ","Modern serviced residence, integrated with retail, walking distance to 163 Retail Park. ","Kediaman servis moden, bersepadu dengan runcit, jarak berjalan kaki ke 163 Retail Park. ","Fully Furnished","Berperabot Lengkap",4800.00,900,2,2026-01-15,6010-7890123,https://www.propertyguru.com.my/bm/senarai-hartanah/arcoris-residences-untuk-disewa-oleh-yen-500197204,"https://www.google.com/maps/place/Arcoris+Residences,+Jalan+Kiara,+Mont+Kiara,+50480+Kuala+Lumpur,+Federal+Territory+of+Kuala+Lumpur/@3.1678768,101.651769,17z/data=!3m1!4b1!4m6!3m5!1s0x31cc48f23533cce9:0x5bc0312ca88adec2!8m2!3d3.1681185!4d101.6518685!16s%2Fg%2F11bvtlr620?entry=ttu&g_ep=EgoyMDI1MTExNy4wIKXMDSoASAFQAw%3D%3D"
14,"Mont Kiara","Seni Mont Kiara ","Artistic luxury condo with private lift lobby and 5-acre garden. ","Kondominium mewah artistik dengan lobi lif peribadi dan taman 5 ekar.","Fully Furnished","Berperabot Lengkap",10000.00,2411,4,2026-03-01,"6010-8901234 ",https://irumah.co/mont-kiara/seni,"https://www.google.com/maps/place/Seni+Mont+Kiara,+Mont+Kiara/"
15,"Mont Kiara","Residensi 22 ","Spacious family luxury unit, low density, near Garden International School. ","Unit keluarga mewah yang luas, kepadatan rendah, berhampiran Sekolah Antarabangsa Garden. ","Fully Furnished","Berperabot Lengkap",9000.00,1878,4,2026-02-15,6010-9012345,https://irumah.co/bm/mont-kiara/residensi-22/photos?utm_source=chatgpt.com,"https://www.google.com/maps/place/Residensi+22,+Mont+Kiara/"
16,Bangsar,"Bangsar Hill Park","Luxury condo near Lorong Maarof, high floor with city view.","Kondominium mewah berhampiran Lorong Maarof, tingkat tinggi dengan pemandangan bandar.","Fully Furnished","Berperabot Lengkap",4000.00,978,2,2025-12-01,6012-1234567,https://www.google.com/search?tbm=isch&q=Bangsar+Hill+Park+Condo,https://www.google.com/maps/search/?api=1&query=Bangsar+Hill+Park+Bangsar
17,Bangsar,"Nadi Bangsar","Modern service residence walking distance to LRT Bangsar.","Kediaman servis moden jarak berjalan kaki ke LRT Bangsar.","Fully Furnished","Berperabot Lengkap",4300.00,990,2,2025-12-05,6012-2345678,https://www.google.com/search?tbm=isch&q=Nadi+Bangsar+Service+Residence,https://www.google.com/maps/search/?api=1&query=Nadi+Bangsar
18,Bangsar,"One Menerung","Exclusive spacious family condo surrounded by greenery.","Kondominium keluarga luas eksklusif dikelilingi kehijauan.","Partially Furnished","Berperabot Separa",15000.00,3282,4,2026-01-01,6012-3456789,https://www.google.com/search?tbm=isch&q=One+Menerung+Bangsar,https://www.google.com/maps/search/?api=1&query=One+Menerung+Bangsar
19,Bangsar,"Sri Penaga","Classic Bangsar condo with resort-style facilities.","Kondominium klasik Bangsar dengan kemudahan gaya resort.",Unfurnished,"Tanpa Perabot",6000.00,1950,3,2025-12-10,6012-4567890,https://www.google.com/search?tbm=isch&q=Sri+Penaga+Condominium+Bangsar,https://www.google.com/maps/search/?api=1&query=Sri+Penaga+Condominium
20,Bangsar,"Zehn Bukit Pantai","Low density luxury unit, quiet area near Pantai Hospital.","Unit mewah kepadatan rendah, kawasan sunyi berhampiran Hospital Pantai.","Partially Furnished","Berperabot Separa",9500.00,2659,4,2025-12-15,6012-5678901,https://www.google.com/search?tbm=isch&q=Zehn+Bukit+Pantai+Bangsar,https://www.google.com/maps/search/?api=1&query=Zehn+Bukit+Pantai
21,Damansara,"Maisson Ara Damansara","Family friendly condo with lush greenery landscaping.","Kondominium mesra keluarga dengan landskap kehijauan yang subur.","Fully Furnished","Berperabot Lengkap",1800.00,675,1,2025-12-01,6012-6789012,https://www.google.com/search?tbm=isch&q=Maisson+Ara+Damansara,https://www.google.com/maps/search/?api=1&query=Maisson+Ara+Damansara
22,Damansara,"H2O Residences","Inspired by aquatic design, extensive water facilities.","Diinspirasikan oleh reka bentuk akuatik, kemudahan air yang luas.","Partially Furnished","Berperabot Separa",2300.00,880,3,2025-12-20,6012-7890123,https://www.google.com/search?tbm=isch&q=H2O+Residences+Ara+Damansara,https://www.google.com/maps/search/?api=1&query=H2O+Residences+Ara+Damansara
23,Damansara,"AraTre Residences","Strategic location near Citta Mall and LRT station.","Lokasi strategik berhampiran Citta Mall dan stesen LRT.","Fully Furnished","Berperabot Lengkap",2600.00,797,2,2025-12-12,6012-8901234,https://www.google.com/search?tbm=isch&q=AraTre+Residences+Ara+Damansara,https://www.google.com/maps/search/?api=1&query=AraTre+Residences
24,Damansara,"The Potpourri","Premium lifestyle suite connected to Citta Mall.","Suite gaya hidup premium yang bersambung dengan Citta Mall.","Fully Furnished","Berperabot Lengkap",2600.00,755,1,2025-12-18,6012-9012345,https://www.google.com/search?tbm=isch&q=The+Potpourri+Ara+Damansara,https://www.google.com/maps/search/?api=1&query=The+Potpourri+Ara+Damansara
25,Damansara,"Eve Suite","Studio unit directly connected to LRT Lembah Subang.","Unit studio bersambung terus ke LRT Lembah Subang.","Fully Furnished","Berperabot Lengkap",1950.00,680,1,2025-12-03,6013-0123456,https://www.google.com/search?tbm=isch&q=Eve+Suite+Ara+Damansara,https://www.google.com/maps/search/?api=1&query=Eve+Suite+Ara+Damansara
26,Cheras,"You City 3","Integrated transit-oriented development near MRT.","Pembangunan berorientasikan transit bersepadu berhampiran MRT.","Fully Furnished","Berperabot Lengkap",2200.00,678,2,2025-12-05,6013-1234567,https://www.google.com/search?tbm=isch&q=You+City+3+Cheras,https://www.google.com/maps/search/?api=1&query=You+City+3+Cheras
27,Cheras,"Sunway Velocity","Prime location connected to shopping mall and medical centre.","Lokasi utama bersambung dengan pusat membeli-belah dan pusat perubatan.","Fully Furnished","Berperabot Lengkap",6800.00,969,3,2026-01-10,6013-2345678,https://www.google.com/search?tbm=isch&q=Sunway+Velocity+Residence,https://www.google.com/maps/search/?api=1&query=Sunway+Velocity+Cheras
28,Cheras,"Emerald 9","Modern living near MRT Taman Suntex with great amenities.","Kehidupan moden berhampiran MRT Taman Suntex dengan kemudahan hebat.","Fully Furnished","Berperabot Lengkap",2300.00,850,2,2025-12-08,6013-3456789,https://www.google.com/search?tbm=isch&q=Emerald+9+Cheras,https://www.google.com/maps/search/?api=1&query=Emerald+9+Cheras
29,Cheras,"Traders Park","Affordable spacious apartment in Balakong area.","Pangsapuri luas mampu milik di kawasan Balakong.","Fully Furnished","Berperabot Lengkap",2299.00,773,3,2025-12-15,6013-4567890,https://www.google.com/search?tbm=isch&q=Dataran+Traders+Square+Cheras,https://www.google.com/maps/search/?api=1&query=Dataran+Traders+Square
30,Cheras,"Saville @ Cheras","Direct link bridge to MRT Sri Raya station.","Jambatan sambungan terus ke stesen MRT Sri Raya.","Fully Furnished","Berperabot Lengkap",1600.00,550,1,2025-12-25,6013-5678901,https://www.google.com/search?tbm=isch&q=Saville+Cheras,https://www.google.com/maps/search/?api=1&query=Saville+Cheras
31,Ampang,"D'Rapport Residences","Resort-style living in the heart of Ampang near embassies.","Kehidupan gaya resort di tengah-tengah Ampang berhampiran kedutaan.","Fully Furnished","Berperabot Lengkap",5300.00,1903,3,2026-01-01,6013-6789012,https://www.google.com/search?tbm=isch&q=DRapport+Residences+Ampang,https://www.google.com/maps/search/?api=1&query=D'Rapport+Residences
32,Ampang,"Neu Suites","Compact modern suites suitable for young professionals.","Suite moden kompak sesuai untuk profesional muda.","Fully Furnished","Berperabot Lengkap",1800.00,460,2,2025-12-10,6013-7890123,https://www.google.com/search?tbm=isch&q=Neu+Suites+Ampang,https://www.google.com/maps/search/?api=1&query=Neu+Suites+Ampang
33,Ampang,"M Suites","Located along Embassy Row, great for expats.","Terletak di sepanjang Embassy Row, bagus untuk ekspatriat.","Partially Furnished","Berperabot Separa",4300.00,1700,3,2025-12-20,6013-8901234,https://www.google.com/search?tbm=isch&q=M+Suites+Ampang,https://www.google.com/maps/search/?api=1&query=M+Suites+Ampang
34,Ampang,"The Elements","High-rise luxury service apartment with city skyline views.","Pangsapuri servis mewah bertingkat tinggi dengan pemandangan latar langit bandar.","Fully Furnished","Berperabot Lengkap",1850.00,705,1,2025-12-05,6013-9012345,https://www.google.com/search?tbm=isch&q=The+Elements+Ampang,https://www.google.com/maps/search/?api=1&query=The+Elements+Ampang
35,Ampang,"Arte Plus","Artistic design suites with unique facilities like floating garden.","Suite reka bentuk artistik dengan kemudahan unik seperti taman terapung.","Fully Furnished","Berperabot Lengkap",1650.00,850,2,2025-12-15,6014-0123456,https://www.google.com/search?tbm=isch&q=Arte+Plus+Ampang,https://www.google.com/maps/search/?api=1&query=Arte+Plus+Ampang
36,"Wangsa Maju","Wangsa Ceria","Double storey terrace house in a quiet neighborhood.","Rumah teres dua tingkat di kawasan kejiranan yang sunyi.","Partially Furnished","Berperabot Separa",2200.00,1500,3,2025-12-01,6014-1234567,https://www.google.com/search?tbm=isch&q=Wangsa+Ceria+House,https://www.google.com/maps/search/?api=1&query=Wangsa+Ceria+Wangsa+Maju
37,"Wangsa Maju","Seasons Garden","Central park residence with easy access to DUKE highway.","Kediaman taman pusat dengan akses mudah ke lebuh raya DUKE.","Partially Furnished","Berperabot Separa",1600.00,770,3,2025-12-10,6014-2345678,https://www.google.com/search?tbm=isch&q=Seasons+Garden+Wangsa+Maju,https://www.google.com/maps/search/?api=1&query=Seasons+Garden+Wangsa+Maju
38,"Wangsa Maju",Hamilton,"Walking distance to Sri Rampai LRT station.","Jarak berjalan kaki ke stesen LRT Sri Rampai.","Fully Furnished","Berperabot Lengkap",2300.00,1000,3,2025-12-05,6014-3456789,https://www.google.com/search?tbm=isch&q=The+Hamilton+Wangsa+Maju,https://www.google.com/maps/search/?api=1&query=The+Hamilton+Wangsa+Maju
39,"Wangsa Maju","Quinn Residence","Low density condo right next to Wangsa Walk Mall.","Kondominium kepadatan rendah bersebelahan Wangsa Walk Mall.","Fully Furnished","Berperabot Lengkap",2500.00,780,2,2026-01-01,6014-4567890,https://www.google.com/search?tbm=isch&q=Quinn+Residence+Wangsa+Maju,https://www.google.com/maps/search/?api=1&query=Quinn+Residence+Wangsa+Maju
40,"Wangsa Maju","Fera Residence","Private modern condo with infinity pool views.","Kondominium moden peribadi dengan pemandangan kolam infiniti.","Partially Furnished","Berperabot Separa",1900.00,820,3,2025-12-15,6014-5678901,https://www.google.com/search?tbm=isch&q=Fera+Residence+Wangsa+Maju,https://www.google.com/maps/search/?api=1&query=Fera+Residence+Wangsa+Maju
41,Setapak,"Residensi Vista Wirajaya","Affordable apartment near TAR UMT and LRT Taman Melati.","Pangsapuri mampu milik berhampiran TAR UMT dan LRT Taman Melati.","Fully Furnished","Berperabot Lengkap",1500.00,884,3,2025-12-01,6014-6789012,https://www.google.com/search?tbm=isch&q=Residensi+Vista+Wirajaya+Setapak,https://www.google.com/maps/search/?api=1&query=Residensi+Vista+Wirajaya
42,Setapak,"Platinum Lake PV12","Spacious condo located near Danau Kota lake garden.","Kondominium luas terletak berhampiran taman tasik Danau Kota.","Fully Furnished","Berperabot Lengkap",1800.00,1207,3,2025-12-12,6014-7890123,https://www.google.com/search?tbm=isch&q=Platinum+Lake+PV12+Setapak,https://www.google.com/maps/search/?api=1&query=Platinum+Lake+PV12
43,Setapak,"Platinum Lake PV20","High density apartment with many student tenants.","Pangsapuri kepadatan tinggi dengan ramai penyewa pelajar.","Partially Furnished","Berperabot Separa",1600.00,1333,4,2025-12-20,6014-8901234,https://www.google.com/search?tbm=isch&q=Platinum+Lake+PV20+Setapak,https://www.google.com/maps/search/?api=1&query=Platinum+Lake+PV20
44,Setapak,"Ameera Residences","Serviced Apartment with affordable pricing, opposite TAR UMT.","Pangsapuri Servis dengan harga mampu milik, bertentangan TAR UMT.","Fully Furnished","Berperabot Lengkap",1350.00,722,2,2025-12-14,6014-9012345,https://www.google.com/search?tbm=isch&q=Ameera+Residences+Setapak,https://www.google.com/maps/search/?api=1&query=Ameera+Residences
45,Setapak,"Danau Kota Suite","Water themed apartment near LRT Danau Kota.","Pangsapuri bertema air berhampiran LRT Danau Kota.","Fully Furnished","Berperabot Lengkap",1400.00,671,2,2025-12-25,6015-0123456,https://www.google.com/search?tbm=isch&q=Danau+Kota+Suite+Setapak,https://www.google.com/maps/search/?api=1&query=Danau+Kota+Suite
46,Puchong,"Lakefront Residence","Modern condo overlooking lake, near IOI Mall Puchong.","Kondominium moden menghadap tasik, berhampiran IOI Mall Puchong.","Fully Furnished","Berperabot Lengkap",1800.00,910,3,2025-12-01,6015-1234567,https://www.google.com/search?tbm=isch&q=Lakefront+Residence+Puchong,https://www.google.com/maps/search/?api=1&query=Lakefront+Residence+Puchong
47,Puchong,"Setia Walk","Integrated lifestyle condo connected to Setia Walk Mall.","Kondominium gaya hidup bersepadu yang disambungkan ke Setia Walk Mall.","Partially Furnished","Berperabot Separa",2200.00,872,2,2025-12-05,6015-2345678,https://www.google.com/search?tbm=isch&q=Setia+Walk+Condominium+Puchong,https://www.google.com/maps/search/?api=1&query=Setia+Walk+Puchong
48,Puchong,"The Wharf Residence","Condo with marina theme, strategic location near LRT.","Kondominium bertema marina, lokasi strategik berhampiran LRT.","Fully Furnished","Berperabot Lengkap",1950.00,780,2,2025-12-10,6015-3456789,https://www.google.com/search?tbm=isch&q=The+Wharf+Residence+Puchong,https://www.google.com/maps/search/?api=1&query=The+Wharf+Residence+Puchong
49,Puchong,"Sky Loft Residence","High rise modern unit with affordable pricing.","Unit moden bertingkat tinggi dengan harga mampu milik.","Partially Furnished","Berperabot Separa",1400.00,650,1,2025-12-15,6015-4567890,https://www.google.com/search?tbm=isch&q=Sky+Loft+Residence+Puchong,https://www.google.com/maps/search/?api=1&query=Sky+Loft+Residence+Puchong
50,Puchong,"M Residence 2","Two bedroom family unit with cozy facilities.","Unit keluarga dua bilik dengan kemudahan yang selesa.","Fully Furnished","Berperabot Lengkap",1600.00,850,2,2025-12-20,6015-5678901,https://www.google.com/search?tbm=isch&q=M+Residence+2+Puchong,https://www.google.com/maps/search/?api=1&query=M+Residence+2+Puchong
51,Subang,"Empire City Damansara","Luxury condominium connected to shopping mall and hotel.","Kondominium mewah yang bersambung dengan pusat beli-belah dan hotel.","Fully Furnished","Berperabot Lengkap",3200.00,1050,2,2026-01-01,6015-6789012,https://www.google.com/search?tbm=isch&q=Empire+City+Damansara+Condominium,https://www.google.com/maps/search/?api=1&query=Empire+City+Damansara
52,Subang,"SS15 Courtyard","Studio unit in the heart of SS15, walking distance to LRT.","Unit studio di tengah-tengah SS15, jarak berjalan kaki ke LRT.","Fully Furnished","Berperabot Lengkap",1600.00,550,1,2025-12-01,6015-7890123,https://www.google.com/search?tbm=isch&q=SS15+Courtyard+Subang,https://www.google.com/maps/search/?api=1&query=SS15+Courtyard
53,Subang,"Summit Subang USJ","Close to Summit USJ shopping mall and Sunway Pyramid.","Dekat dengan pusat membeli-belah Summit USJ dan Sunway Pyramid.","Fully Furnished","Berperabot Lengkap",1900.00,820,2,2025-12-10,6015-8901234,https://www.google.com/search?tbm=isch&q=Summit+Subang+USJ,https://www.google.com/maps/search/?api=1&query=Summit+Subang+USJ
54,Subang,"Subang Olives","Family friendly condo near schools and amenities.","Kondominium mesra keluarga berhampiran sekolah dan kemudahan.","Partially Furnished","Berperabot Separa",2100.00,950,3,2025-12-15,6015-9012345,https://www.google.com/search?tbm=isch&q=Subang+Olives+Condominium,https://www.google.com/maps/search/?api=1&query=Subang+Olives
55,Subang,"Da:Men Residence","Integrated with Da:men mall, near USJ LRT station.","Bersepadu dengan pusat beli-belah Da:men, dekat dengan stesen LRT USJ.","Fully Furnished","Berperabot Lengkap",2300.00,880,2,2025-12-20,6016-0123456,https://www.google.com/search?tbm=isch&q=Damen+Residence+Subang,https://www.google.com/maps/search/?api=1&query=Damen+Residence
56,Cyberjaya,"Tamarind Suites","Modern serviced apartment near universities and tech parks.","Pangsapuri servis moden berhampiran universiti dan taman teknologi.","Fully Furnished","Berperabot Lengkap",1500.00,689,1,2025-12-01,6016-1234567,https://www.google.com/search?tbm=isch&q=Tamarind+Suites+Cyberjaya,https://www.google.com/maps/search/?api=1&query=Tamarind+Suites+Cyberjaya
57,Cyberjaya,"D'Pulze Residence","Integrated with shopping mall and direct access to offices.","Bersepadu dengan pusat membeli-belah dan akses terus ke pejabat.","Fully Furnished","Berperabot Lengkap",1700.00,710,2,2025-12-05,6016-2345678,https://www.google.com/search?tbm=isch&q=DPulze+Residence+Cyberjaya,https://www.google.com/maps/search/?api=1&query=DPulze+Residence
58,Cyberjaya,"Shaftsbury Cyberjaya","Spacious apartment near Cyberjaya Lake Gardens.","Pangsapuri luas berhampiran Taman Tasik Cyberjaya.","Partially Furnished","Berperabot Separa",1600.00,850,2,2025-12-10,6016-3456789,https://www.google.com/search?tbm=isch&q=Shaftsbury+Square+Cyberjaya,https://www.google.com/maps/search/?api=1&query=Shaftsbury+Cyberjaya
59,Cyberjaya,"Vivo Residences","Stylish modern apartment suitable for tech professionals.","Pangsapuri moden bergaya yang sesuai untuk profesional teknologi.","Fully Furnished","Berperabot Lengkap",1800.00,760,2,2025-12-15,6016-4567890,https://www.google.com/search?tbm=isch&q=Vivo+Residences+Cyberjaya,https://www.google.com/maps/search/?api=1&query=Vivo+Residences+Cyberjaya
60,Cyberjaya,"Canary Residence","Contemporary design with green environment and lake views.","Reka bentuk kontemporari dengan persekitaran hijau dan pemandangan tasik.","Fully Furnished","Berperabot Lengkap",1650.00,720,1,2025-12-20,6016-5678901,https://www.google.com/search?tbm=isch&q=Canary+Residence+Cyberjaya,https://www.google.com/maps/search/?api=1&query=Canary+Residence+Cyberjaya
61,Putrajaya,"Santorini at Putrajaya","Mediterranean inspired condo with lake view.","Kondominium berinspirasikan Mediterranean dengan pemandangan tasik.","Fully Furnished","Berperabot Lengkap",2500.00,1050,3,2026-01-01,6016-6789012,https://www.google.com/search?tbm=isch&q=Santorini+Putrajaya,https://www.google.com/maps/search/?api=1&query=Santorini+Putrajaya
62,Putrajaya,"Panorama Residence","High floor unit overlooking Putrajaya Lake.","Unit tingkat tinggi menghadap Tasik Putrajaya.","Fully Furnished","Berperabot Lengkap",2300.00,980,2,2025-12-01,6016-7890123,https://www.google.com/search?tbm=isch&q=Panorama+Residence+Putrajaya,https://www.google.com/maps/search/?api=1&query=Panorama+Residence+Putrajaya
63,Putrajaya,"Suasana Lumayan","Serene residence in the heart of Putrajaya.","Kediaman yang tenang di tengah-tengah Putrajaya.","Partially Furnished","Berperabot Separa",2100.00,900,3,2025-12-10,6016-8901234,https://www.google.com/search?tbm=isch&q=Suasana+Lumayan+Putrajaya,https://www.google.com/maps/search/?api=1&query=Suasana+Lumayan
64,Putrajaya,"Platinum Lake PV15","Modern condo with water theme and resort facilities.","Kondominium moden bertema air dengan kemudahan resort.","Fully Furnished","Berperabot Lengkap",2200.00,920,2,2025-12-15,6016-9012345,https://www.google.com/search?tbm=isch&q=Platinum+Lake+PV15+Putrajaya,https://www.google.com/maps/search/?api=1&query=Platinum+Lake+PV15+Putrajaya
65,Putrajaya,"The Horizon Residence","Luxury unit with panoramic city views.","Unit mewah dengan pemandangan panoramik bandar.","Fully Furnished","Berperabot Lengkap",2800.00,1100,3,2025-12-20,6017-0123456,https://www.google.com/search?tbm=isch&q=The+Horizon+Residence+Putrajaya,https://www.google.com/maps/search/?api=1&query=The+Horizon+Residence+Putrajaya
66,Klang,"Idaman Residensi","Affordable family unit in Klang town center.","Unit keluarga mampu milik di pusat bandar Klang.","Partially Furnished","Berperabot Separa",1300.00,950,3,2025-12-01,6017-1234567,https://www.google.com/search?tbm=isch&q=Idaman+Residensi+Klang,https://www.google.com/maps/search/?api=1&query=Idaman+Residensi+Klang
67,Klang,"Andalucia Apartment","Spacious apartment near shops and amenities.","Pangsapuri luas berhampiran kedai dan kemudahan.","Fully Furnished","Berperabot Lengkap",1400.00,900,3,2025-12-05,6017-2345678,https://www.google.com/search?tbm=isch&q=Andalucia+Apartment+Klang,https://www.google.com/maps/search/?api=1&query=Andalucia+Apartment+Klang
68,Klang,"Taman Chi Liung","Double storey terrace house in established neighborhood.","Rumah teres dua tingkat di kawasan kejiranan yang mantap.","Partially Furnished","Berperabot Separa",1600.00,1500,4,2025-12-10,6017-3456789,https://www.google.com/search?tbm=isch&q=Taman+Chi+Liung+Klang,https://www.google.com/maps/search/?api=1&query=Taman+Chi+Liung+Klang
69,Klang,"Parkland OUG","Condominium with easy access to Federal Highway.","Kondominium dengan akses mudah ke Lebuh Raya Persekutuan.","Fully Furnished","Berperabot Lengkap",1700.00,880,2,2025-12-15,6017-4567890,https://www.google.com/search?tbm=isch&q=Parkland+OUG+Klang,https://www.google.com/maps/search/?api=1&query=Parkland+OUG+Klang
70,Klang,"Hicom Glenmarie","Near Shah Alam and industrial area, good for working professionals.","Dekat Shah Alam dan kawasan perindustrian, sesuai untuk profesional yang bekerja.","Fully Furnished","Berperabot Lengkap",1500.00,820,2,2025-12-20,6017-5678901,https://www.google.com/search?tbm=isch&q=Hicom+Glenmarie+Klang,https://www.google.com/maps/search/?api=1&query=Hicom+Glenmarie
71,Kajang,"Residensi Platinum","Affordable apartment near Kajang town center.","Pangsapuri mampu milik berhampiran pusat bandar Kajang.","Fully Furnished","Berperabot Lengkap",1200.00,850,3,2025-12-01,6017-6789012,https://www.google.com/search?tbm=isch&q=Residensi+Platinum+Kajang,https://www.google.com/maps/search/?api=1&query=Residensi+Platinum+Kajang
72,Kajang,"Metia Residence","Modern condo with good connectivity to MRT.","Kondominium moden dengan sambungan yang baik ke MRT.","Fully Furnished","Berperabot Lengkap",1600.00,920,2,2025-12-05,6017-7890123,https://www.google.com/search?tbm=isch&q=Metia+Residence+Kajang,https://www.google.com/maps/search/?api=1&query=Metia+Residence+Kajang
73,Kajang,"Parkhill Residence","Hillside condo with scenic valley views.","Kondominium di lereng bukit dengan pemandangan lembah yang indah.","Partially Furnished","Berperabot Separa",1800.00,980,3,2025-12-10,6017-8901234,https://www.google.com/search?tbm=isch&q=Parkhill+Residence+Kajang,https://www.google.com/maps/search/?api=1&query=Parkhill+Residence+Kajang
74,Kajang,"The Zest","Convenient location near Kajang MRT station.","Lokasi yang mudah berhampiran stesen MRT Kajang.","Fully Furnished","Berperabot Lengkap",1500.00,750,2,2025-12-15,6017-9012345,https://www.google.com/search?tbm=isch&q=The+Zest+Kajang,https://www.google.com/maps/search/?api=1&query=The+Zest+Kajang
75,Kajang,"Seri Saujana","Spacious family apartment with greenery surrounding.","Pangsapuri keluarga yang luas dengan kehijauan di sekeliling.","Fully Furnished","Berperabot Lengkap",1400.00,950,3,2025-12-20,6018-0123456,https://www.google.com/search?tbm=isch&q=Seri+Saujana+Kajang,https://www.google.com/maps/search/?api=1&query=Seri+Saujana+Kajang
76,"Petaling Jaya","Tropicana Gardens","Luxury serviced residence integrated with shopping mall.","Kediaman servis mewah yang bersepadu dengan pusat membeli-belah.","Fully Furnished","Berperabot Lengkap",4500.00,1200,2,2026-01-01,6018-1234567,https://www.google.com/search?tbm=isch&q=Tropicana+Gardens+Residence,https://www.google.com/maps/search/?api=1&query=Tropicana+Gardens
77,"Petaling Jaya","PJ Trade Centre","Office suite converted to residential, near LRT.","Suite pejabat ditukar kepada kediaman, berhampiran LRT.","Partially Furnished","Berperabot Separa",1800.00,750,1,2025-12-01,6018-2345678,https://www.google.com/search?tbm=isch&q=PJ+Trade+Centre,https://www.google.com/maps/search/?api=1&query=PJ+Trade+Centre
78,"Petaling Jaya","The Scott Garden","Modern integrated development with shopping podium.","Pembangunan bersepadu moden dengan podium membeli-belah.","Fully Furnished","Berperabot Lengkap",2500.00,950,2,2025-12-05,6018-3456789,https://www.google.com/search?tbm=isch&q=The+Scott+Garden+PJ,https://www.google.com/maps/search/?api=1&query=The+Scott+Garden
79,"Petaling Jaya","One Damansara","Luxury condo in upscale Damansara area.","Kondominium mewah di kawasan Damansara yang mewah.","Fully Furnished","Berperabot Lengkap",3500.00,1100,3,2025-12-10,6018-4567890,https://www.google.com/search?tbm=isch&q=One+Damansara+PJ,https://www.google.com/maps/search/?api=1&query=One+Damansara
80,"Petaling Jaya","Sunway Nexis","Direct link to Sunway Pyramid and Sunway University.","Sambungan terus ke Sunway Pyramid dan Universiti Sunway.","Fully Furnished","Berperabot Lengkap",2200.00,850,2,2025-12-15,6018-5678901,https://www.google.com/search?tbm=isch&q=Sunway+Nexis+PJ,https://www.google.com/maps/search/?api=1&query=Sunway+Nexis
81,"Shah Alam","i-City Residence","Modern condo near the famous i-City theme park.","Kondominium moden berhampiran taman tema i-City yang terkenal.","Fully Furnished","Berperabot Lengkap",1600.00,800,2,2025-12-01,6018-6789012,https://www.google.com/search?tbm=isch&q=iCity+Residence+Shah+Alam,https://www.google.com/maps/search/?api=1&query=iCity+Residence
82,"Shah Alam","Alam Sanjung","Spacious family apartment near Section 13.","Pangsapuri keluarga yang luas berhampiran Seksyen 13.","Partially Furnished","Berperabot Separa",1400.00,950,3,2025-12-05,6018-7890123,https://www.google.com/search?tbm=isch&q=Alam+Sanjung+Shah+Alam,https://www.google.com/maps/search/?api=1&query=Alam+Sanjung
83,"Shah Alam","Greenhill Residence","Hillside condo with nature views.","Kondominium di lereng bukit dengan pemandangan alam semula jadi.","Fully Furnished","Berperabot Lengkap",1700.00,900,2,2025-12-10,6018-8901234,https://www.google.com/search?tbm=isch&q=Greenhill+Residence+Shah+Alam,https://www.google.com/maps/search/?api=1&query=Greenhill+Residence
84,"Shah Alam","Casa Tiara","Low density condo in peaceful neighborhood.","Kondominium kepadatan rendah di kawasan kejiranan yang aman.","Fully Furnished","Berperabot Lengkap",1800.00,920,3,2025-12-15,6018-9012345,https://www.google.com/search?tbm=isch&q=Casa+Tiara+Shah+Alam,https://www.google.com/maps/search/?api=1&query=Casa+Tiara+Shah+Alam
85,"Shah Alam","Saujana KLIA","Near KLIA and airport, convenient for frequent travelers.","Dekat KLIA dan lapangan terbang, mudah untuk pengembara kerap.","Fully Furnished","Berperabot Lengkap",1500.00,850,2,2025-12-20,6019-0123456,https://www.google.com/search?tbm=isch&q=Saujana+KLIA,https://www.google.com/maps/search/?api=1&query=Saujana+KLIA
86,"Seri Kembangan","Sutera Avenue","Studio unit near UPM and shopping mall.","Unit studio berhampiran UPM dan pusat membeli-belah.","Fully Furnished","Berperabot Lengkap",1200.00,550,1,2025-12-01,6019-1234567,https://www.google.com/search?tbm=isch&q=Sutera+Avenue+Seri+Kembangan,https://www.google.com/maps/search/?api=1&query=Sutera+Avenue
87,"Seri Kembangan","Seri Intan Apartment","Affordable unit popular with students.","Unit mampu milik popular dengan pelajar.","Partially Furnished","Berperabot Separa",1000.00,850,3,2025-12-05,6019-2345678,https://www.google.com/search?tbm=isch&q=Seri+Intan+Apartment+Seri+Kembangan,https://www.google.com/maps/search/?api=1&query=Seri+Intan+Apartment
88,"Seri Kembangan","The Mines Residence","Luxurious condo overlooking The Mines lake.","Kondominium mewah menghadap tasik The Mines.","Fully Furnished","Berperabot Lengkap",2500.00,1050,3,2025-12-10,6019-3456789,https://www.google.com/search?tbm=isch&q=The+Mines+Residence,https://www.google.com/maps/search/?api=1&query=The+Mines+Residence
89,"Seri Kembangan","Bayu Tasik 2","Convenient location near highway and amenities.","Lokasi yang mudah berhampiran lebuh raya dan kemudahan.","Fully Furnished","Berperabot Lengkap",1300.00,800,2,2025-12-15,6019-4567890,https://www.google.com/search?tbm=isch&q=Bayu+Tasik+2+Seri+Kembangan,https://www.google.com/maps/search/?api=1&query=Bayu+Tasik+2
90,"Seri Kembangan","Rimba Residence","Family apartment with good facilities.","Pangsapuri keluarga dengan kemudahan yang baik.","Fully Furnished","Berperabot Lengkap",1400.00,900,3,2025-12-20,6019-5678901,https://www.google.com/search?tbm=isch&q=Rimba+Residence+Seri+Kembangan,https://www.google.com/maps/search/?api=1&query=Rimba+Residence
91,Semenyih,"Casa Residenza","New modern condo with resort facilities.","Kondominium moden baharu dengan kemudahan resort.","Fully Furnished","Berperabot Lengkap",1400.00,850,2,2025-12-01,6019-6789012,https://www.google.com/search?tbm=isch&q=Casa+Residenza+Semenyih,https://www.google.com/maps/search/?api=1&query=Casa+Residenza+Semenyih
92,Semenyih,"Taman Bukit Serdang","Affordable family terrace house.","Rumah teres keluarga mampu milik.","Partially Furnished","Berperabot Separa",1300.00,1400,3,2025-12-05,6019-7890123,https://www.google.com/search?tbm=isch&q=Taman+Bukit+Serdang+Semenyih,https://www.google.com/maps/search/?api=1&query=Taman+Bukit+Serdang
93,Semenyih,"Palm Garden","Peaceful condo with greenery and nature.","Kondominium yang aman dengan kehijauan dan alam semula jadi.","Fully Furnished","Berperabot Lengkap",1500.00,900,2,2025-12-10,6019-8901234,https://www.google.com/search?tbm=isch&q=Palm+Garden+Semenyih,https://www.google.com/search?tbm=isch&q=Palm+Garden+Semenyih
94,Semenyih,"Riverside Residence","Condo overlooking river and hills.","Kondominium menghadap sungai dan bukit.","Fully Furnished","Berperabot Lengkap",1600.00,920,3,2025-12-15,6019-9012345,https://www.google.com/search?tbm=isch&q=Riverside+Residence+Semenyih,https://www.google.com/maps/search/?api=1&query=Riverside+Residence+Semenyih
95,Semenyih,"Spring Ville","Low cost apartment near town center.","Pangsapuri kos rendah berhampiran pusat bandar.","Partially Furnished","Berperabot Separa",1100.00,750,2,2025-12-20,6020-0123456,https://www.google.com/search?tbm=isch&q=Spring+Ville+Semenyih,https://www.google.com/maps/search/?api=1&query=Spring+Ville+Semenyih
96,Rawang,"Bandar Country Homes","Double storey terrace in gated community.","Rumah teres dua tingkat dalam komuniti berpagar.","Partially Furnished","Berperabot Separa",1500.00,1600,4,2025-12-01,6020-1234567,https://www.google.com/search?tbm=isch&q=Bandar+Country+Homes+Rawang,https://www.google.com/maps/search/?api=1&query=Bandar+Country+Homes
97,Rawang,"Astetica Residences","Modern serviced apartment near town.","Pangsapuri servis moden berhampiran bandar.","Fully Furnished","Berperabot Lengkap",1300.00,750,2,2025-12-05,6020-2345678,https://www.google.com/search?tbm=isch&q=Astetica+Residences+Rawang,https://www.google.com/maps/search/?api=1&query=Astetica+Residences
98,Rawang,"Lagenda Villa","Villa style family home with private garden.","Rumah keluarga gaya vila dengan taman peribadi.","Partially Furnished","Berperabot Separa",2000.00,2000,4,2025-12-10,6020-3456789,https://www.google.com/search?tbm=isch&q=Lagenda+Villa+Rawang,https://www.google.com/maps/search/?api=1&query=Lagenda+Villa+Rawang
99,Rawang,"Emerald West","Condo with good connectivity to KL.","Kondominium dengan sambungan yang baik ke KL.","Fully Furnished","Berperabot Lengkap",1400.00,850,2,2025-12-15,6020-4567890,https://www.google.com/search?tbm=isch&q=Emerald+West+Rawang,https://www.google.com/maps/search/?api=1&query=Emerald+West+Rawang
100,Rawang,"Tasik Puteri","Lakeside apartment with peaceful environment.","Pangsapuri tepi tasik dengan persekitaran yang aman.","Fully Furnished","Berperabot Lengkap",1200.00,800,2,2025-12-20,6020-5678901,https://www.google.com/search?tbm=isch&q=Tasik+Puteri+Rawang,https://www.google.com/maps/search/?api=1&query=Tasik+Puteri+Rawang
101,"Batu Caves","Selayang 18","Affordable condo near Batu Caves and Selayang Hospital.","Kondominium mampu milik berhampiran Batu Caves dan Hospital Selayang.","Fully Furnished","Berperabot Lengkap",1100.00,700,2,2025-12-01,6020-6789012,https://www.google.com/search?tbm=isch&q=Selayang+18,https://www.google.com/maps/search/?api=1&query=Selayang+18
102,"Batu Caves","Desa Putra","Budget friendly family apartment.","Pangsapuri keluarga mesra bajet.","Partially Furnished","Berperabot Separa",1000.00,850,3,2025-12-05,6020-7890123,https://www.google.com/search?tbm=isch&q=Desa+Putra+Batu+Caves,https://www.google.com/maps/search/?api=1&query=Desa+Putra"""

# Parse CSV
import io
reader = csv.DictReader(io.StringIO(csv_data))

# Insert data
inserted_count = 0
for row in reader:
    try:
        # Clean and prepare data
        property_id = int(row['id'])
        area = row['area'].strip()
        title = row['title'].strip()
        description_en = row['description_en'].strip()
        description_ms = row['description_ms'].strip()
        furnishing_en = row['furnishing_en'].strip()
        furnishing_ms = row['furnishing_ms'].strip()
        price = float(row['price'])
        sqft = int(row['sqft'])
        bedroom = int(row['bedroom'])
        move_in_date = row['move_in_date'].strip()
        agent_phone = row['agent_phone'].strip()
        image_url = row['image_url'].strip()
        map_url = row['map_url'].strip()
        
        # Insert into database using tagged template
        result = db`
            INSERT INTO properties (
                id, area, title, description_en, description_ms,
                furnishing_en, furnishing_ms, price, sqft, bedroom,
                move_in_date, agent_phone, image_url, map_url
            ) VALUES (
                ${property_id}, ${area}, ${title}, ${description_en}, ${description_ms},
                ${furnishing_en}, ${furnishing_ms}, ${price}, ${sqft}, ${bedroom},
                ${move_in_date}, ${agent_phone}, ${image_url}, ${map_url}
            )
            ON CONFLICT (id) DO UPDATE SET
                area = EXCLUDED.area,
                title = EXCLUDED.title,
                description_en = EXCLUDED.description_en,
                description_ms = EXCLUDED.description_ms,
                furnishing_en = EXCLUDED.furnishing_en,
                furnishing_ms = EXCLUDED.furnishing_ms,
                price = EXCLUDED.price,
                sqft = EXCLUDED.sqft,
                bedroom = EXCLUDED.bedroom,
                move_in_date = EXCLUDED.move_in_date,
                agent_phone = EXCLUDED.agent_phone,
                image_url = EXCLUDED.image_url,
                map_url = EXCLUDED.map_url
        `
        
        inserted_count += 1
        print(f"[v0] Inserted property {property_id}: {title}")
        
    except Exception as e:
        print(f"[v0] Error inserting row {row.get('id', 'unknown')}: {str(e)}")
        continue

print(f"\n[v0] Successfully imported {inserted_count} properties into the database!")
